### PR TITLE
Updated Az upgrade target from 4.6.1 to 4.8.0

### LINKED ISSUE #52: Targeted Az version to upgrade to 4.7
**Component**
[X] PowerShell module
[] VSCode extension
[] Other

**Description of the new feature**
The target version of Az should be 4.7

### PR DESCRIPTION
**Pull request by keithbabinec**
Resolves #52

### CODE REVIEW

**Comment by dcaro** [comment]
@dingmeng-xue PTAL

**Comment by keithbabinec** [comment]
@dingmeng-xue or @wyunchi-ms -- we are still looking for review on this PR and on PR #65

**Comment by keithbabinec** [comment]
@dcaro -- FYI since 4.8.0 is out now, I just updated this PR to use that instead. Still waiting on signoff from one dev team member.

**Comment by wyunchi-ms** [comment]
LGTM~

**Pull request merged**
